apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  template:
    spec:
      containers:
        - name: backend
          envFrom:
            - secretRef:
                name: backend
          env:
            - name: PINO_LOG_PRETTY
              value: "1"
            - name: LOG_LEVEL
              value: debug
            - name: VERSION
              value: dev
            - name: REPLICATED_API_TOKEN
              value: patch-me
            - name: REPLICATED_APP
              value: patch-me
            - name: REPLICATED_CHANNEL_ID
              value: patch-me




